[package]
name = "rust_linux2linux_udp"
version = "0.1.0"
edition = "2021"
authors = ["qsbye"]

[dependencies]
# base64编码
base64 = "0.22.1"
# 命令行cli工具
clap = { version = "4.5.32", features = ["derive"] }
# 网络协议栈
edge-net = { version = "0.9.3", features = ["std"] }
edge-raw = { path = "./static/edge-raw", version = "0.4.0", features = ["std"] }
edge-nal = "0.4.2"
# systemd操作接口
# libsystemd = { version = "0.7.0", path = "./static/libsystemd" }
systemctl = "0.4.0"
# 异步框架
tokio = "1.44.1"
# 异步框架
futures-lite = "2.6.0"
# usb设备通信(纯rust)
nusb = { version = "0.2.0-beta", path = "./static/nusb" } 
# 虚拟网卡接口
tappers = "0.4.2"
# 内嵌文件
embed-file = "0.2.0"
# 日志记录
env_logger = "0.11.7"
# mosh命令行
moshudp = { path = "./static/moshudp" }
# 文件同步
bitar = { path = "./static/bita/bitar" }
fast_rsync = { path = "./static/fast_rsync" }
# wasm运行时
wasmer = "5.0.4"
# wasm开发框架
xtask-wasm = "0.3.1"
# 数据库(wasm版)
sqlite-wasm-rs = { version = "0.3.1", default-features = false, features = ["precompiled"] }
