# [workspace.package]
# version = "0.0.1"
# edition = "2024"
# authors = ["qsbye"]
# description = "byeefree命令行工具集(适用于四旋翼无人机等机器人任务)."
# rust-version = "1.85.0"

# [workspace]
# resolver = '2'
# members = []

[package]
name = "byeefree_rs"
# version.workspace = true
# edition.workspace = true
# authors.workspace = true
# description.workspace = true
# rust-version.workspace = true
default-run = "byeefree"
version = "0.0.1"
edition = "2024"
authors = ["qsbye"]
description = "byeefree命令行工具集(适用于四旋翼无人机等机器人任务)."
rust-version = "1.85.0"
build = "build.rs"

[[bin]]
name = "byeefree"
path = "src/bin/byeefree.rs"
doc = false

[[bin]]
name = "installer"
path = "src/bin/installer.rs"
doc = false

[[example]]
name = "database_login"
path = "examples/database_login"
features = ["kitesql"]

[[example]]
name = "database_sql"
path = "examples/database_sql"
features = ["kitesql"]

[dependencies]
# base64编码
base64 = "0.22.1"
# 命令行cli工具
clap = { version = "4.5.32", features = ["derive"] }
# 网络协议栈
edge-net = { version = "0.9.3", features = ["std"] }
edge-raw = { path = "./static/edge-raw", version = "0.4.0", features = ["std"] }
edge-nal = "0.4.2"
# systemd操作接口
# libsystemd = { version = "0.7.0", path = "./static/libsystemd" }
systemctl = "0.4.0"
# 异步框架
tokio = "1.44.1"
# 异步框架
futures-lite = "2.6.0"
# usb设备通信(纯rust)
nusb = { version = "0.2.0-beta", path = "./static/nusb" } 
# 虚拟网卡接口
tappers = "0.4.2"
# 内嵌文件
embed-file = "0.2.0"
# 日志记录
env_logger = "0.11.7"
# mosh命令行
moshudp = { path = "./static/moshudp" }
# 文件同步
bitar = { path = "./static/bita/bitar" }
fast_rsync = { path = "./static/fast_rsync" }
# wasm运行时
wasmtime = { version = "32.0.0", path = "./static/wasmtime/crates/wasmtime" }
wasmtime-wasi = { version = "32.0.0", path = "./static/wasmtime/crates/wasi" }
wasi-common = { version = "32.0.0", path = "./static/wasmtime/crates/wasi-common" }
wasmtime-cli = { version = "32.0.0", path = "./static/wasmtime", features = ["run", "serve", "explore", "wast", "cache", "compile", "cranelift", "objdump"] }
# wasm开发框架
xtask-wasm = "0.3.1"
# 错误处理
anyhow = "1.0.97"
# SM4国密算法(对称加密)
sm4-gcm = { version = "0.1.2", path = "./static/sm4-gcm" }
# SM9国密算法(非对称加密)
sm9 = { version = "0.3.2", path = "./static/sm9" }
# 16进制转换
hex = "0.4.3"
# 临时文件
tempfile = "3.19.1"
# 数据库(SQL型)
kite_sql = { version = "0.1.1", path = "./static/KiteSQL", optional = true }
# 唯一识别码
uuid = { version = "1.16.0", features = ["v4"] }
# 复杂命令解析
shell-words = "1.1.0"
# 字节处理
bytes = "1.10.1"
# c标准库(处理stdio)
libc = "0.2.171"
# stdio重定向
stdio-override = "0.2.0"
# 系统cpu等使用情况
systemstat = { version = "0.2.4", path = "./static/systemstat" }
# 日志记录
log = "0.4.27"
# 时间格式化输出
chrono = "0.4.40"
# 嵌入文件夹
rust-embed = "8.6.0"
# sqlite3数据库(纯rust)
prsqlite = { version = "0.1.0", path = "./static/prsqlite" }
# kv值存储
redb = { version = "2.4.0", path = "./static/redb" }

# build.rs依赖
[build-dependencies]
# 时间格式化输出
chrono = "0.4.40"

# 配置条件编译
[features]
kitesql = ["kite_sql"]
